server:
  port: 8002

spring:
  application:
    name: USER-SERVICE
    
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: My410$Su
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
    - optional:configserver:http:\\localhost:8888
