server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suja-28/DEPARTMENT-SERVICE.git
          clone-on-start: true
          default-label: dev
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
